services:
  - type: web
    name: foodies
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: foodies-disk
      mountPath: /opt/render/project/src
      sizeGB: 1 